### ISSUE TITLE
Issues with setting up HTTPS Portal

### ISSUE THREAD

**Issue by ipGhost** [Gozargah/Marzban-examples#13]
Hi,

The HTTP portal and servers are working fine. I have set up a domain with TLS. But I'm not able to change to HTTP portal to a HTTPS portal. I've followed the steps in your installation guide, but was unable to fix this.

Please give me a detailed guide for how to setup up a HTTPS admin portal

**Comment by xray108** [comment]
The same situation. When I start a docker container with TLS settings, the container cannot start.

env file:
`SUDO_USERNAME = "admin"
SUDO_PASSWORD = "z1vnukr8"


XRAY_SUBSCRIPTION_URL_PREFIX = "https://mydomain"
UVICORN_PORT = 8880
UVICORN_SSL_CERTFILE = "/var/lib/marzban/certs/fullchain.pem"
UVICORN_SSL_KEYFILE = "/var/lib/marzban/certs/key.pem"`

I am attaching the log:
`INFO  [alembic.runtime.migration] Context impl SQLiteImpl.
INFO  [alembic.runtime.migration] Will assume non-transactional DDL.
INFO  [alembic.runtime.migration] Running upgrade  -> 94a5cc12c0d6, init user table
INFO  [alembic.runtime.migration] Running upgrade 94a5cc12c0d6 -> 3cf36a5fde73, init system table
INFO  [alembic.runtime.migration] Running upgrade 3cf36a5fde73 -> 9d5a518ae432, init jwt table
INFO  [alembic.runtime.migration] Running upgrade 9d5a518ae432 -> 9b60be6cd0a2, add created_at field to users table
INFO  [alembic.runtime.migration] Running upgrade 9b60be6cd0a2 -> 8e849e06f131, proxy table
INFO  [alembic.runtime.migration] Running upgrade 8e849e06f131 -> 671621870b02, init admin
INFO  [alembic.runtime.migration] Running upgrade 671621870b02 -> e91236993f1a, inbounds table & excluded_inbounds
INFO  [alembic.runtime.migration] Running upgrade e91236993f1a -> b3378dc6de01, hosts
INFO  [alembic.runtime.migration] Running upgrade 671621870b02 -> d02dcfbf1517, add UserUsageResetLogs Model and data_limit_strategy field to user
INFO  [alembic.runtime.migration] Running upgrade d02dcfbf1517, b3378dc6de01 -> ece13c4c6f65, empty message
INFO  [alembic.runtime.migration] Running upgrade ece13c4c6f65 -> b15eba6e5867, add host and sni columns to hosts table
INFO  [alembic.runtime.migration] Running upgrade b15eba6e5867 -> 51e941ed9018, deactive user status
INFO  [alembic.runtime.migration] Running upgrade 51e941ed9018 -> e3f0e888a563, rename deactive status to disabled
INFO  [alembic.runtime.migration] Running upgrade e3f0e888a563 -> 7cbe9d91ac11, ProxyHost: security added
INFO  [alembic.runtime.migration] Running upgrade 7cbe9d91ac11 -> 5b84d88804a1, fix
INFO  [alembic.runtime.migration] Running upgrade 5b84d88804a1 -> fad8b1997c3a, case insensitive username
INFO  [alembic.runtime.migration] Context impl SQLiteImpl.
INFO  [alembic.runtime.migration] Will assume non-transactional DDL.
INFO  [alembic.runtime.migration] Context impl SQLiteImpl.
INFO  [alembic.runtime.migration] Will assume non-transactional DDL.
INFO  [alembic.runtime.migration] Context impl SQLiteImpl.
INFO  [alembic.runtime.migration] Will assume non-transactional DDL.
INFO  [alembic.runtime.migration] Context impl SQLiteImpl.
INFO  [alembic.runtime.migration] Will assume non-transactional DDL.
INFO  [alembic.runtime.migration] Context impl SQLiteImpl.
INFO  [alembic.runtime.migration] Will assume non-transactional DDL.
INFO  [alembic.runtime.migration] Context impl SQLiteImpl.
INFO  [alembic.runtime.migration] Will assume non-transactional DDL.
INFO  [alembic.runtime.migration] Context impl SQLiteImpl.
INFO  [alembic.runtime.migration] Will assume non-transactional DDL.
INFO  [alembic.runtime.migration] Context impl SQLiteImpl.
INFO  [alembic.runtime.migration] Will assume non-transactional DDL.
INFO  [alembic.runtime.migration] Context impl SQLiteImpl.
INFO  [alembic.runtime.migration] Will assume non-transactional DDL.
INFO  [alembic.runtime.migration] Context impl SQLiteImpl.
INFO  [alembic.runtime.migration] Will assume non-transactional DDL.`

**Comment by SaintShit** [comment]
Hi, are u using fully single port?

**Comment by ipGhost** [comment]
No, I’m using multi-port

**Comment by ipGhost** [comment]
Bump

**Comment by SaintShit** [comment]
Hi, check https://github.com/Gozargah/Marzban/#configuration

you have to set `UVICORN_SSL_CERTFILE` and `UVICORN_SSL_KEYFILE`

**Comment by harukodi** [comment]
```yaml

services:
  marzban:
    image: gozargah/marzban:latest
    restart: always
    env_file: env
    network_mode: host

    environment:
      SQLALCHEMY_DATABASE_URL: "sqlite:////var/lib/marzban/db.sqlite3"
      XRAY_JSON: "/xray_config.json"

    volumes:
      - ./xray_config.json:/xray_config.json
      - ./certs:/var/lib/marzban/certs/ #should be where the certs are getting collected when running the python script 

```

**Comment by harukodi** [comment]
```yaml
services:
  marzban:
    image: gozargah/marzban:latest
    restart: always
    env_file: env
    network_mode: host

    environment:
      SQLALCHEMY_DATABASE_URL: "sqlite:////var/lib/marzban/db.sqlite3"
      XRAY_JSON: "/xray_config.json"

    volumes:
      - ./xray_config.json:/xray_config.json
      - /var/lib/marzban:/var/lib/marzban #open /var/lib/marzban/certs/fullchain.pem: no such file or directory
```
This is wrong try to change the path when editing your volume and try the config above this one thanks!
